# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo Hi
    silent: true
  test:
    cmds:
      - go test -timeout 10s -v  ./...
  test-race:
    cmds:
      - go test -race -timeout 30s -v ./...
