# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo Hi
    silent: true
  test:
    cmds:
      - go test -timeout 10s {{.CLI_ARGS}}  ./...
  benchmark:
      cmds:
        - go test -timeout 10s -bench=. {{.CLI_ARGS}}  ./...
  test-all:
    cmds:
      - task: test
      - task: benchmark
  test-race:
    cmds:
      - go test -race -timeout 30s {{.CLI_ARGS}} ./...
  clean:
    cmds:
      - go clean -testcache -cache
  cover-html:
    cmds:
      - rm -f cover*
      - go test -v -coverprofile cover.out ./...
      - go tool cover -html=cover.out -o cover.html
